// <auto-generated />
using System;
using Jira.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jira.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191025122634_AddedJSprints")]
    partial class AddedJSprints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jira.Core.Data.Entities.JProject", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Icon");

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Key");

                    b.Property<string>("LeadKey");

                    b.Property<string>("Name");

                    b.Property<string>("ProjectTypeKey");

                    b.Property<bool>("Simplified");

                    b.Property<string>("Style");

                    b.HasKey("Id");

                    b.ToTable("JiraProjects");
                });

            modelBuilder.Entity("Jira.Core.Data.Entities.JSprint", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime?>("CompleteDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("Goal");

                    b.Property<string>("Name");

                    b.Property<int>("OriginBoardId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("JiraSprints");
                });

            modelBuilder.Entity("Jira.Core.Data.Entities.JUser", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountId");

                    b.Property<string>("AccountType");

                    b.Property<string>("AvatarUrl");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Locale");

                    b.Property<string>("Name");

                    b.Property<string>("Self");

                    b.Property<string>("TimeZone");

                    b.HasKey("Key");

                    b.ToTable("JiraUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
